
# default configuration settings for PostgreSQL database

drivername = 'postgres'
username = 'postgres'   # User can specify custom username
password = 'password'   # User can specify custom password
host = '127.0.0.1'      # Default PostgreSQL host
port = 5432             # Default PostgreSQL port



